version: '3.2'
services:

  mysqlDB:
    image: mysql
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=simple
    - MYSQL_DATABASE=firstdb
    - MYSQL_USER=user
    - MYSQL_PASSWORD=pass123

  redisDB:
    image: redis
    ports:
    - "6379:6379"

  sparkApp:
    image: gettyimages/spark
    volumes:
    - ~/dockerVol:/usr/spark-2.3.1/sparkJob
    links:
    - mysqlDB:mysql
    - redisDB:redis
    ports:
    - "4040:4040"
